name: Test API (Job in a container)
on: [push, workflow_dispatch]

jobs:
  test-api:
    runs-on: ubuntu-latest
    container: ubuntu:20.04 # we need to install curl here (it was already installed on our runner machine but won't be in our container)
    services: # in github actions, we can use multiple service containers
      app: # we need to upload our image to dockerhub to use it in github actions # container no 1
        image: alialaa17/simple-node-api
        ports:
          - 3001:3000
        env:
          MONGO_HOSTNAME: mongo # mongo here is the service name we defined below
      mongo: # container no 2
        image: mongo # image that exists in dockerhub
        ports:
          - 27017:27017
    steps: # our steps will run in this ubuntu:20.04 (container)
      - name: Install curl
        run: |
          apt-get -y update
          apt-get -y install curl
      - name: Dump Services Context
        run: echo '${{ toJson(job.services) }}'
      # now we are going to communicate with our service by exposing a port
      - name: Post a user
        run: 'curl -X POST http://localhost:3001/api/users -H ''Content-Type: application/json'' -d ''{"username": "hello","address": "dwded"}'''
      - name: Get Users
        run: curl http://localhost:3001/api/users